# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: nightly-2022-07-18 # for ghc 9.2

# Using intensional functions GHC
# NOTE: This should eventually point to a publicly visible repository.
compiler: ghc-git-cac571902c6c34d6e7aca7f9d52dd63d15e4789d-quick
compiler-repository: git.bahj.com:intensional-functions-ghc

# User packages to be built.
packages:
- .

# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps:
  - git: git.bahj.com:intensional-functions-lib
    commit: d5f9799a657a266d732f4ee94472009b34553a16
  - git: git.bahj.com:intensional-functions-closure-engine
    commit: b233af828121dc5f54fa0b1e4d5dbd0b46e8e44d
  - dequeue-0.1.12@sha256:547c2a71819dca0ae1bf7c15fb290b39f80d5d9a6f9985a06a1cb8645b578df2,855
