# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: nightly-2022-07-18 # for ghc 9.2

# Using intensional functions GHC
compiler: ghc-git-12cb0cf2e6eb91ec7a97f1cd05f6682b34cb9d97-quick
compiler-repository: https://github.com/zepalmer/intensional-functions-ghc.git

# User packages to be built.
packages:
- .

# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps:
  - git: https://github.com/zepalmer/intensional-functions-lib
    commit: 3ed99513f26b6c8feec6bc6b57e9544a636ff759
  - git: https://github.com/zepalmer/intensional-functions-closure-engine
    commit: 6a75e1582b7dfd1ab354eada68fc81529dd5965f
  - dequeue-0.1.12@sha256:547c2a71819dca0ae1bf7c15fb290b39f80d5d9a6f9985a06a1cb8645b578df2,855
